### ISSUE TITLE
Add Installation Instructions

### ISSUE THREAD

**Issue by LindaOrtega** [kadena-io/pact-lsp#11]
It would be useful to add installation instructions to the README.

Here's how Pact documents building from source:
https://github.com/kadena-io/pact-lsp

**Comment by severian1778** [comment]
The installation instructions are very frusting w.r.t Vim.  We install Plug and lsp and lsp-settings but its just no clear how to install it,  We place the If statement provided in .vimrc and run LspInstallServer but no beuno likely because it needs pact and there is no mention of "how" to initialize the server by pointing it to pact.
